// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mgrsvr_protocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mgrsvr_5fprotocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_mgrsvr_5fprotocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mgrsvr_5fprotocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mgrsvr_5fprotocol_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mgrsvr_5fprotocol_2eproto;
namespace mgr_svr {
class CONSLOE_CMD;
class CONSLOE_CMDDefaultTypeInternal;
extern CONSLOE_CMDDefaultTypeInternal _CONSLOE_CMD_default_instance_;
class PACKAGE;
class PACKAGEDefaultTypeInternal;
extern PACKAGEDefaultTypeInternal _PACKAGE_default_instance_;
class RESPONSE;
class RESPONSEDefaultTypeInternal;
extern RESPONSEDefaultTypeInternal _RESPONSE_default_instance_;
class START_SVR;
class START_SVRDefaultTypeInternal;
extern START_SVRDefaultTypeInternal _START_SVR_default_instance_;
class UPDATE_SVR;
class UPDATE_SVRDefaultTypeInternal;
extern UPDATE_SVRDefaultTypeInternal _UPDATE_SVR_default_instance_;
}  // namespace mgr_svr
PROTOBUF_NAMESPACE_OPEN
template<> ::mgr_svr::CONSLOE_CMD* Arena::CreateMaybeMessage<::mgr_svr::CONSLOE_CMD>(Arena*);
template<> ::mgr_svr::PACKAGE* Arena::CreateMaybeMessage<::mgr_svr::PACKAGE>(Arena*);
template<> ::mgr_svr::RESPONSE* Arena::CreateMaybeMessage<::mgr_svr::RESPONSE>(Arena*);
template<> ::mgr_svr::START_SVR* Arena::CreateMaybeMessage<::mgr_svr::START_SVR>(Arena*);
template<> ::mgr_svr::UPDATE_SVR* Arena::CreateMaybeMessage<::mgr_svr::UPDATE_SVR>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mgr_svr {

enum SEVER_TYPE : int {
  ERROR_SVR = 0,
  MGR_SVR = 1,
  GATE_SVR = 2,
  GAME_SVR = 3,
  LOGIN_SVR = 4,
  DATA_SVR = 5,
  HTTP_SVR = 6,
  CTRL_SVR = 7,
  SEVER_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  SEVER_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool SEVER_TYPE_IsValid(int value);
constexpr SEVER_TYPE SEVER_TYPE_MIN = ERROR_SVR;
constexpr SEVER_TYPE SEVER_TYPE_MAX = CTRL_SVR;
constexpr int SEVER_TYPE_ARRAYSIZE = SEVER_TYPE_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SEVER_TYPE_descriptor();
template<typename T>
inline const std::string& SEVER_TYPE_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SEVER_TYPE>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SEVER_TYPE_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    SEVER_TYPE_descriptor(), enum_t_value);
}
inline bool SEVER_TYPE_Parse(
    const std::string& name, SEVER_TYPE* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SEVER_TYPE>(
    SEVER_TYPE_descriptor(), name, value);
}
enum PROTOCOL_ID : int {
  ERR_PRO = 0,
  HEART = 1,
  START = 2,
  RES_START = 3,
  STOP = 4,
  RES_STOP = 5,
  UPDATE = 6,
  RES_UPDATE = 7,
  CMD = 8,
  RES_CMD = 9,
  PROTOCOL_ID_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  PROTOCOL_ID_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool PROTOCOL_ID_IsValid(int value);
constexpr PROTOCOL_ID PROTOCOL_ID_MIN = ERR_PRO;
constexpr PROTOCOL_ID PROTOCOL_ID_MAX = RES_CMD;
constexpr int PROTOCOL_ID_ARRAYSIZE = PROTOCOL_ID_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PROTOCOL_ID_descriptor();
template<typename T>
inline const std::string& PROTOCOL_ID_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PROTOCOL_ID>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PROTOCOL_ID_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PROTOCOL_ID_descriptor(), enum_t_value);
}
inline bool PROTOCOL_ID_Parse(
    const std::string& name, PROTOCOL_ID* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PROTOCOL_ID>(
    PROTOCOL_ID_descriptor(), name, value);
}
enum REQ_ERROR : int {
  ERR_REQ = 0,
  SUCCESS = 1,
  ERR_TYPE = 2,
  ERR_ID = 3,
  ERR_VERSION = 4,
  ERR_TIMEOUT = 5,
  ERR_LINK_NUM = 6,
  ERR_EXIST = 7,
  ERR_ALLOC = 8,
  REQ_ERROR_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  REQ_ERROR_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool REQ_ERROR_IsValid(int value);
constexpr REQ_ERROR REQ_ERROR_MIN = ERR_REQ;
constexpr REQ_ERROR REQ_ERROR_MAX = ERR_ALLOC;
constexpr int REQ_ERROR_ARRAYSIZE = REQ_ERROR_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* REQ_ERROR_descriptor();
template<typename T>
inline const std::string& REQ_ERROR_Name(T enum_t_value) {
  static_assert(::std::is_same<T, REQ_ERROR>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function REQ_ERROR_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    REQ_ERROR_descriptor(), enum_t_value);
}
inline bool REQ_ERROR_Parse(
    const std::string& name, REQ_ERROR* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<REQ_ERROR>(
    REQ_ERROR_descriptor(), name, value);
}
enum CMD_TYPE : int {
  ERR_CMD = 0,
  RESTART = 1,
  RECONF = 2,
  CLOSE_ALL_SVR = 3,
  CLOSE_SVR_BY_TYPE = 4,
  CLOSE_SVR_BY_ID = 5,
  TEST_CHAT = 6,
  STOP_SVR = 7,
  CMD_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  CMD_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool CMD_TYPE_IsValid(int value);
constexpr CMD_TYPE CMD_TYPE_MIN = ERR_CMD;
constexpr CMD_TYPE CMD_TYPE_MAX = STOP_SVR;
constexpr int CMD_TYPE_ARRAYSIZE = CMD_TYPE_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CMD_TYPE_descriptor();
template<typename T>
inline const std::string& CMD_TYPE_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CMD_TYPE>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CMD_TYPE_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CMD_TYPE_descriptor(), enum_t_value);
}
inline bool CMD_TYPE_Parse(
    const std::string& name, CMD_TYPE* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CMD_TYPE>(
    CMD_TYPE_descriptor(), name, value);
}
// ===================================================================

class PACKAGE :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mgr_svr.PACKAGE) */ {
 public:
  PACKAGE();
  virtual ~PACKAGE();

  PACKAGE(const PACKAGE& from);
  PACKAGE(PACKAGE&& from) noexcept
    : PACKAGE() {
    *this = ::std::move(from);
  }

  inline PACKAGE& operator=(const PACKAGE& from) {
    CopyFrom(from);
    return *this;
  }
  inline PACKAGE& operator=(PACKAGE&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PACKAGE& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PACKAGE* internal_default_instance() {
    return reinterpret_cast<const PACKAGE*>(
               &_PACKAGE_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PACKAGE& a, PACKAGE& b) {
    a.Swap(&b);
  }
  inline void Swap(PACKAGE* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PACKAGE* New() const final {
    return CreateMaybeMessage<PACKAGE>(nullptr);
  }

  PACKAGE* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PACKAGE>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PACKAGE& from);
  void MergeFrom(const PACKAGE& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PACKAGE* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mgr_svr.PACKAGE";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mgrsvr_5fprotocol_2eproto);
    return ::descriptor_table_mgrsvr_5fprotocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPackageFieldNumber = 3,
    kIdFieldNumber = 1,
    kSvrIdFieldNumber = 2,
  };
  // bytes package = 3;
  void clear_package();
  const std::string& package() const;
  void set_package(const std::string& value);
  void set_package(std::string&& value);
  void set_package(const char* value);
  void set_package(const void* value, size_t size);
  std::string* mutable_package();
  std::string* release_package();
  void set_allocated_package(std::string* package);

  // int32 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::int32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 svr_id = 2;
  void clear_svr_id();
  ::PROTOBUF_NAMESPACE_ID::int32 svr_id() const;
  void set_svr_id(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:mgr_svr.PACKAGE)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr package_;
  ::PROTOBUF_NAMESPACE_ID::int32 id_;
  ::PROTOBUF_NAMESPACE_ID::int32 svr_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mgrsvr_5fprotocol_2eproto;
};
// -------------------------------------------------------------------

class START_SVR :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mgr_svr.START_SVR) */ {
 public:
  START_SVR();
  virtual ~START_SVR();

  START_SVR(const START_SVR& from);
  START_SVR(START_SVR&& from) noexcept
    : START_SVR() {
    *this = ::std::move(from);
  }

  inline START_SVR& operator=(const START_SVR& from) {
    CopyFrom(from);
    return *this;
  }
  inline START_SVR& operator=(START_SVR&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const START_SVR& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const START_SVR* internal_default_instance() {
    return reinterpret_cast<const START_SVR*>(
               &_START_SVR_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(START_SVR& a, START_SVR& b) {
    a.Swap(&b);
  }
  inline void Swap(START_SVR* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline START_SVR* New() const final {
    return CreateMaybeMessage<START_SVR>(nullptr);
  }

  START_SVR* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<START_SVR>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const START_SVR& from);
  void MergeFrom(const START_SVR& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(START_SVR* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mgr_svr.START_SVR";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mgrsvr_5fprotocol_2eproto);
    return ::descriptor_table_mgrsvr_5fprotocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLinkSvrFieldNumber = 3,
    kVersionFieldNumber = 2,
    kTypeFieldNumber = 1,
  };
  // repeated int32 link_svr = 3;
  int link_svr_size() const;
  void clear_link_svr();
  ::PROTOBUF_NAMESPACE_ID::int32 link_svr(int index) const;
  void set_link_svr(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_link_svr(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      link_svr() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_link_svr();

  // string version = 2;
  void clear_version();
  const std::string& version() const;
  void set_version(const std::string& value);
  void set_version(std::string&& value);
  void set_version(const char* value);
  void set_version(const char* value, size_t size);
  std::string* mutable_version();
  std::string* release_version();
  void set_allocated_version(std::string* version);

  // int32 type = 1;
  void clear_type();
  ::PROTOBUF_NAMESPACE_ID::int32 type() const;
  void set_type(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:mgr_svr.START_SVR)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > link_svr_;
  mutable std::atomic<int> _link_svr_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr version_;
  ::PROTOBUF_NAMESPACE_ID::int32 type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mgrsvr_5fprotocol_2eproto;
};
// -------------------------------------------------------------------

class UPDATE_SVR :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mgr_svr.UPDATE_SVR) */ {
 public:
  UPDATE_SVR();
  virtual ~UPDATE_SVR();

  UPDATE_SVR(const UPDATE_SVR& from);
  UPDATE_SVR(UPDATE_SVR&& from) noexcept
    : UPDATE_SVR() {
    *this = ::std::move(from);
  }

  inline UPDATE_SVR& operator=(const UPDATE_SVR& from) {
    CopyFrom(from);
    return *this;
  }
  inline UPDATE_SVR& operator=(UPDATE_SVR&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UPDATE_SVR& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UPDATE_SVR* internal_default_instance() {
    return reinterpret_cast<const UPDATE_SVR*>(
               &_UPDATE_SVR_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(UPDATE_SVR& a, UPDATE_SVR& b) {
    a.Swap(&b);
  }
  inline void Swap(UPDATE_SVR* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UPDATE_SVR* New() const final {
    return CreateMaybeMessage<UPDATE_SVR>(nullptr);
  }

  UPDATE_SVR* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UPDATE_SVR>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UPDATE_SVR& from);
  void MergeFrom(const UPDATE_SVR& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UPDATE_SVR* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mgr_svr.UPDATE_SVR";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mgrsvr_5fprotocol_2eproto);
    return ::descriptor_table_mgrsvr_5fprotocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLinkSvrFieldNumber = 3,
    kVersionFieldNumber = 2,
    kTypeFieldNumber = 1,
  };
  // repeated int32 link_svr = 3;
  int link_svr_size() const;
  void clear_link_svr();
  ::PROTOBUF_NAMESPACE_ID::int32 link_svr(int index) const;
  void set_link_svr(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_link_svr(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      link_svr() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_link_svr();

  // string version = 2;
  void clear_version();
  const std::string& version() const;
  void set_version(const std::string& value);
  void set_version(std::string&& value);
  void set_version(const char* value);
  void set_version(const char* value, size_t size);
  std::string* mutable_version();
  std::string* release_version();
  void set_allocated_version(std::string* version);

  // int32 type = 1;
  void clear_type();
  ::PROTOBUF_NAMESPACE_ID::int32 type() const;
  void set_type(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:mgr_svr.UPDATE_SVR)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > link_svr_;
  mutable std::atomic<int> _link_svr_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr version_;
  ::PROTOBUF_NAMESPACE_ID::int32 type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mgrsvr_5fprotocol_2eproto;
};
// -------------------------------------------------------------------

class CONSLOE_CMD :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mgr_svr.CONSLOE_CMD) */ {
 public:
  CONSLOE_CMD();
  virtual ~CONSLOE_CMD();

  CONSLOE_CMD(const CONSLOE_CMD& from);
  CONSLOE_CMD(CONSLOE_CMD&& from) noexcept
    : CONSLOE_CMD() {
    *this = ::std::move(from);
  }

  inline CONSLOE_CMD& operator=(const CONSLOE_CMD& from) {
    CopyFrom(from);
    return *this;
  }
  inline CONSLOE_CMD& operator=(CONSLOE_CMD&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CONSLOE_CMD& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CONSLOE_CMD* internal_default_instance() {
    return reinterpret_cast<const CONSLOE_CMD*>(
               &_CONSLOE_CMD_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(CONSLOE_CMD& a, CONSLOE_CMD& b) {
    a.Swap(&b);
  }
  inline void Swap(CONSLOE_CMD* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CONSLOE_CMD* New() const final {
    return CreateMaybeMessage<CONSLOE_CMD>(nullptr);
  }

  CONSLOE_CMD* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CONSLOE_CMD>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CONSLOE_CMD& from);
  void MergeFrom(const CONSLOE_CMD& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CONSLOE_CMD* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mgr_svr.CONSLOE_CMD";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mgrsvr_5fprotocol_2eproto);
    return ::descriptor_table_mgrsvr_5fprotocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContextFieldNumber = 2,
    kCmdIdFieldNumber = 1,
  };
  // bytes context = 2;
  void clear_context();
  const std::string& context() const;
  void set_context(const std::string& value);
  void set_context(std::string&& value);
  void set_context(const char* value);
  void set_context(const void* value, size_t size);
  std::string* mutable_context();
  std::string* release_context();
  void set_allocated_context(std::string* context);

  // int32 cmd_id = 1;
  void clear_cmd_id();
  ::PROTOBUF_NAMESPACE_ID::int32 cmd_id() const;
  void set_cmd_id(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:mgr_svr.CONSLOE_CMD)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr context_;
  ::PROTOBUF_NAMESPACE_ID::int32 cmd_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mgrsvr_5fprotocol_2eproto;
};
// -------------------------------------------------------------------

class RESPONSE :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mgr_svr.RESPONSE) */ {
 public:
  RESPONSE();
  virtual ~RESPONSE();

  RESPONSE(const RESPONSE& from);
  RESPONSE(RESPONSE&& from) noexcept
    : RESPONSE() {
    *this = ::std::move(from);
  }

  inline RESPONSE& operator=(const RESPONSE& from) {
    CopyFrom(from);
    return *this;
  }
  inline RESPONSE& operator=(RESPONSE&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RESPONSE& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RESPONSE* internal_default_instance() {
    return reinterpret_cast<const RESPONSE*>(
               &_RESPONSE_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(RESPONSE& a, RESPONSE& b) {
    a.Swap(&b);
  }
  inline void Swap(RESPONSE* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RESPONSE* New() const final {
    return CreateMaybeMessage<RESPONSE>(nullptr);
  }

  RESPONSE* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RESPONSE>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RESPONSE& from);
  void MergeFrom(const RESPONSE& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RESPONSE* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mgr_svr.RESPONSE";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mgrsvr_5fprotocol_2eproto);
    return ::descriptor_table_mgrsvr_5fprotocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContextFieldNumber = 2,
    kErrorFieldNumber = 1,
  };
  // bytes context = 2;
  void clear_context();
  const std::string& context() const;
  void set_context(const std::string& value);
  void set_context(std::string&& value);
  void set_context(const char* value);
  void set_context(const void* value, size_t size);
  std::string* mutable_context();
  std::string* release_context();
  void set_allocated_context(std::string* context);

  // .mgr_svr.REQ_ERROR error = 1;
  void clear_error();
  ::mgr_svr::REQ_ERROR error() const;
  void set_error(::mgr_svr::REQ_ERROR value);

  // @@protoc_insertion_point(class_scope:mgr_svr.RESPONSE)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr context_;
  int error_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mgrsvr_5fprotocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PACKAGE

// int32 id = 1;
inline void PACKAGE::clear_id() {
  id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PACKAGE::id() const {
  // @@protoc_insertion_point(field_get:mgr_svr.PACKAGE.id)
  return id_;
}
inline void PACKAGE::set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:mgr_svr.PACKAGE.id)
}

// int32 svr_id = 2;
inline void PACKAGE::clear_svr_id() {
  svr_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PACKAGE::svr_id() const {
  // @@protoc_insertion_point(field_get:mgr_svr.PACKAGE.svr_id)
  return svr_id_;
}
inline void PACKAGE::set_svr_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  svr_id_ = value;
  // @@protoc_insertion_point(field_set:mgr_svr.PACKAGE.svr_id)
}

// bytes package = 3;
inline void PACKAGE::clear_package() {
  package_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& PACKAGE::package() const {
  // @@protoc_insertion_point(field_get:mgr_svr.PACKAGE.package)
  return package_.GetNoArena();
}
inline void PACKAGE::set_package(const std::string& value) {
  
  package_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mgr_svr.PACKAGE.package)
}
inline void PACKAGE::set_package(std::string&& value) {
  
  package_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mgr_svr.PACKAGE.package)
}
inline void PACKAGE::set_package(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  package_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mgr_svr.PACKAGE.package)
}
inline void PACKAGE::set_package(const void* value, size_t size) {
  
  package_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mgr_svr.PACKAGE.package)
}
inline std::string* PACKAGE::mutable_package() {
  
  // @@protoc_insertion_point(field_mutable:mgr_svr.PACKAGE.package)
  return package_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* PACKAGE::release_package() {
  // @@protoc_insertion_point(field_release:mgr_svr.PACKAGE.package)
  
  return package_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void PACKAGE::set_allocated_package(std::string* package) {
  if (package != nullptr) {
    
  } else {
    
  }
  package_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), package);
  // @@protoc_insertion_point(field_set_allocated:mgr_svr.PACKAGE.package)
}

// -------------------------------------------------------------------

// START_SVR

// int32 type = 1;
inline void START_SVR::clear_type() {
  type_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 START_SVR::type() const {
  // @@protoc_insertion_point(field_get:mgr_svr.START_SVR.type)
  return type_;
}
inline void START_SVR::set_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:mgr_svr.START_SVR.type)
}

// string version = 2;
inline void START_SVR::clear_version() {
  version_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& START_SVR::version() const {
  // @@protoc_insertion_point(field_get:mgr_svr.START_SVR.version)
  return version_.GetNoArena();
}
inline void START_SVR::set_version(const std::string& value) {
  
  version_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mgr_svr.START_SVR.version)
}
inline void START_SVR::set_version(std::string&& value) {
  
  version_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mgr_svr.START_SVR.version)
}
inline void START_SVR::set_version(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  version_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mgr_svr.START_SVR.version)
}
inline void START_SVR::set_version(const char* value, size_t size) {
  
  version_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mgr_svr.START_SVR.version)
}
inline std::string* START_SVR::mutable_version() {
  
  // @@protoc_insertion_point(field_mutable:mgr_svr.START_SVR.version)
  return version_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* START_SVR::release_version() {
  // @@protoc_insertion_point(field_release:mgr_svr.START_SVR.version)
  
  return version_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void START_SVR::set_allocated_version(std::string* version) {
  if (version != nullptr) {
    
  } else {
    
  }
  version_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), version);
  // @@protoc_insertion_point(field_set_allocated:mgr_svr.START_SVR.version)
}

// repeated int32 link_svr = 3;
inline int START_SVR::link_svr_size() const {
  return link_svr_.size();
}
inline void START_SVR::clear_link_svr() {
  link_svr_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 START_SVR::link_svr(int index) const {
  // @@protoc_insertion_point(field_get:mgr_svr.START_SVR.link_svr)
  return link_svr_.Get(index);
}
inline void START_SVR::set_link_svr(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  link_svr_.Set(index, value);
  // @@protoc_insertion_point(field_set:mgr_svr.START_SVR.link_svr)
}
inline void START_SVR::add_link_svr(::PROTOBUF_NAMESPACE_ID::int32 value) {
  link_svr_.Add(value);
  // @@protoc_insertion_point(field_add:mgr_svr.START_SVR.link_svr)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
START_SVR::link_svr() const {
  // @@protoc_insertion_point(field_list:mgr_svr.START_SVR.link_svr)
  return link_svr_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
START_SVR::mutable_link_svr() {
  // @@protoc_insertion_point(field_mutable_list:mgr_svr.START_SVR.link_svr)
  return &link_svr_;
}

// -------------------------------------------------------------------

// UPDATE_SVR

// int32 type = 1;
inline void UPDATE_SVR::clear_type() {
  type_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UPDATE_SVR::type() const {
  // @@protoc_insertion_point(field_get:mgr_svr.UPDATE_SVR.type)
  return type_;
}
inline void UPDATE_SVR::set_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:mgr_svr.UPDATE_SVR.type)
}

// string version = 2;
inline void UPDATE_SVR::clear_version() {
  version_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& UPDATE_SVR::version() const {
  // @@protoc_insertion_point(field_get:mgr_svr.UPDATE_SVR.version)
  return version_.GetNoArena();
}
inline void UPDATE_SVR::set_version(const std::string& value) {
  
  version_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mgr_svr.UPDATE_SVR.version)
}
inline void UPDATE_SVR::set_version(std::string&& value) {
  
  version_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mgr_svr.UPDATE_SVR.version)
}
inline void UPDATE_SVR::set_version(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  version_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mgr_svr.UPDATE_SVR.version)
}
inline void UPDATE_SVR::set_version(const char* value, size_t size) {
  
  version_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mgr_svr.UPDATE_SVR.version)
}
inline std::string* UPDATE_SVR::mutable_version() {
  
  // @@protoc_insertion_point(field_mutable:mgr_svr.UPDATE_SVR.version)
  return version_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* UPDATE_SVR::release_version() {
  // @@protoc_insertion_point(field_release:mgr_svr.UPDATE_SVR.version)
  
  return version_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void UPDATE_SVR::set_allocated_version(std::string* version) {
  if (version != nullptr) {
    
  } else {
    
  }
  version_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), version);
  // @@protoc_insertion_point(field_set_allocated:mgr_svr.UPDATE_SVR.version)
}

// repeated int32 link_svr = 3;
inline int UPDATE_SVR::link_svr_size() const {
  return link_svr_.size();
}
inline void UPDATE_SVR::clear_link_svr() {
  link_svr_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UPDATE_SVR::link_svr(int index) const {
  // @@protoc_insertion_point(field_get:mgr_svr.UPDATE_SVR.link_svr)
  return link_svr_.Get(index);
}
inline void UPDATE_SVR::set_link_svr(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  link_svr_.Set(index, value);
  // @@protoc_insertion_point(field_set:mgr_svr.UPDATE_SVR.link_svr)
}
inline void UPDATE_SVR::add_link_svr(::PROTOBUF_NAMESPACE_ID::int32 value) {
  link_svr_.Add(value);
  // @@protoc_insertion_point(field_add:mgr_svr.UPDATE_SVR.link_svr)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
UPDATE_SVR::link_svr() const {
  // @@protoc_insertion_point(field_list:mgr_svr.UPDATE_SVR.link_svr)
  return link_svr_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
UPDATE_SVR::mutable_link_svr() {
  // @@protoc_insertion_point(field_mutable_list:mgr_svr.UPDATE_SVR.link_svr)
  return &link_svr_;
}

// -------------------------------------------------------------------

// CONSLOE_CMD

// int32 cmd_id = 1;
inline void CONSLOE_CMD::clear_cmd_id() {
  cmd_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CONSLOE_CMD::cmd_id() const {
  // @@protoc_insertion_point(field_get:mgr_svr.CONSLOE_CMD.cmd_id)
  return cmd_id_;
}
inline void CONSLOE_CMD::set_cmd_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  cmd_id_ = value;
  // @@protoc_insertion_point(field_set:mgr_svr.CONSLOE_CMD.cmd_id)
}

// bytes context = 2;
inline void CONSLOE_CMD::clear_context() {
  context_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CONSLOE_CMD::context() const {
  // @@protoc_insertion_point(field_get:mgr_svr.CONSLOE_CMD.context)
  return context_.GetNoArena();
}
inline void CONSLOE_CMD::set_context(const std::string& value) {
  
  context_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mgr_svr.CONSLOE_CMD.context)
}
inline void CONSLOE_CMD::set_context(std::string&& value) {
  
  context_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mgr_svr.CONSLOE_CMD.context)
}
inline void CONSLOE_CMD::set_context(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  context_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mgr_svr.CONSLOE_CMD.context)
}
inline void CONSLOE_CMD::set_context(const void* value, size_t size) {
  
  context_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mgr_svr.CONSLOE_CMD.context)
}
inline std::string* CONSLOE_CMD::mutable_context() {
  
  // @@protoc_insertion_point(field_mutable:mgr_svr.CONSLOE_CMD.context)
  return context_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CONSLOE_CMD::release_context() {
  // @@protoc_insertion_point(field_release:mgr_svr.CONSLOE_CMD.context)
  
  return context_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CONSLOE_CMD::set_allocated_context(std::string* context) {
  if (context != nullptr) {
    
  } else {
    
  }
  context_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), context);
  // @@protoc_insertion_point(field_set_allocated:mgr_svr.CONSLOE_CMD.context)
}

// -------------------------------------------------------------------

// RESPONSE

// .mgr_svr.REQ_ERROR error = 1;
inline void RESPONSE::clear_error() {
  error_ = 0;
}
inline ::mgr_svr::REQ_ERROR RESPONSE::error() const {
  // @@protoc_insertion_point(field_get:mgr_svr.RESPONSE.error)
  return static_cast< ::mgr_svr::REQ_ERROR >(error_);
}
inline void RESPONSE::set_error(::mgr_svr::REQ_ERROR value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:mgr_svr.RESPONSE.error)
}

// bytes context = 2;
inline void RESPONSE::clear_context() {
  context_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& RESPONSE::context() const {
  // @@protoc_insertion_point(field_get:mgr_svr.RESPONSE.context)
  return context_.GetNoArena();
}
inline void RESPONSE::set_context(const std::string& value) {
  
  context_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mgr_svr.RESPONSE.context)
}
inline void RESPONSE::set_context(std::string&& value) {
  
  context_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mgr_svr.RESPONSE.context)
}
inline void RESPONSE::set_context(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  context_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mgr_svr.RESPONSE.context)
}
inline void RESPONSE::set_context(const void* value, size_t size) {
  
  context_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mgr_svr.RESPONSE.context)
}
inline std::string* RESPONSE::mutable_context() {
  
  // @@protoc_insertion_point(field_mutable:mgr_svr.RESPONSE.context)
  return context_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* RESPONSE::release_context() {
  // @@protoc_insertion_point(field_release:mgr_svr.RESPONSE.context)
  
  return context_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void RESPONSE::set_allocated_context(std::string* context) {
  if (context != nullptr) {
    
  } else {
    
  }
  context_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), context);
  // @@protoc_insertion_point(field_set_allocated:mgr_svr.RESPONSE.context)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mgr_svr

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::mgr_svr::SEVER_TYPE> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::mgr_svr::SEVER_TYPE>() {
  return ::mgr_svr::SEVER_TYPE_descriptor();
}
template <> struct is_proto_enum< ::mgr_svr::PROTOCOL_ID> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::mgr_svr::PROTOCOL_ID>() {
  return ::mgr_svr::PROTOCOL_ID_descriptor();
}
template <> struct is_proto_enum< ::mgr_svr::REQ_ERROR> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::mgr_svr::REQ_ERROR>() {
  return ::mgr_svr::REQ_ERROR_descriptor();
}
template <> struct is_proto_enum< ::mgr_svr::CMD_TYPE> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::mgr_svr::CMD_TYPE>() {
  return ::mgr_svr::CMD_TYPE_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_mgrsvr_5fprotocol_2eproto
